@extends('layouts.app')
@section('title', 'Dashboard')
@section('header', 'Dashboard')
@section('content')
<div class="container">
    <div class="row mb-4">
        <div class="col-md-12 text-center">
            <h1>Admin Dashboard</h1>
            <p>Welcome, Admin! Manage your inventory efficiently.</p>
        </div>
    </div>

    <div class="row">
        <!-- Quick Access Cards -->
        <div class="col-md-4">
            <div class="card text-white bg-primary mb-3">
                <div class="card-header">Quick Access</div>
                <div class="card-body">
                    <h5 class="card-title">Reports</h5>
                    <p class="card-text">Generate and view detailed reports of inventory activity.</p>
                    <a href="#" class="btn btn-light">Go to Reports</a>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card text-white bg-success mb-3">
                <div class="card-header">Quick Access</div>
                <div class="card-body">
                    <h5 class="card-title">Manage Items</h5>
                    <p class="card-text">Add, edit, or delete items in your inventory.</p>
                    <a href="{{ route('barang.index') }}" class="btn btn-light">Manage Items</a>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card text-white bg-warning mb-3">
                <div class="card-header">Quick Access</div>
                <div class="card-body">
                    <h5 class="card-title">Manage Users</h5>
                    <p class="card-text">Control user access and manage accounts.</p>
                    <a href="#" class="btn btn-light">Manage Users</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Recent Activities Section -->
    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Recent Activities</div>
                <div class="card-body">
                    <ul class="list-group">
                        <li class="list-group-item">User John added a new item: "Laptop Dell XPS 13"</li>
                        <li class="list-group-item">Report generated by Admin on 2025-01-22</li>
                        <li class="list-group-item">User Sarah updated item stock: "Wireless Mouse"</li>
                        <li class="list-group-item">Admin deleted user "Guest123"</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection